Reorganize the ARCloud document structure
magicleap/developer-portal-docs pull request #12
Opened 2023-02-09 22:35 UTC by grozdanov

- Add ARCloud Overview section
- Simplify the instructions by assembling all the steps in one page per deployment.

2023-02-15 14:49 UTC, singlerider requested changes
We do not use `.mdx` extensions. Please convert to `.md`.

2023-02-15 14:49 UTC, singlerider commented on docs/guides/arcloud/_category_.json
> +}
Please add newline at EOF

2023-02-15 14:51 UTC, grozdanov commented on docs/guides/arcloud/_category_.json
> +}
@singlerider, is there any reason not to use `.mdx` extension ?

2023-02-15 14:52 UTC, singlerider commented on docs/guides/arcloud/_category_.json
> +}
It's not necessary to do so and I would like to keep our docs consistent with the other pages, none of which use this extension.

2023-02-15 15:02 UTC, grozdanov commented on docs/guides/arcloud/_install_istio_aws.mdx
> +
Where do you an issue with the formatting ?

2023-02-15 15:11 UTC, singlerider commented on docs/guides/arcloud/_install_istio_aws.mdx
> +
It's consistent throughout.

For example, the headings (`# Heading 1`) don't have an extra newline to give it "room to breathe."

2023-02-15 15:22 UTC, singlerider commented on docs/guides/arcloud/_install_istio_aws.mdx
> +
<img width="474" alt="Screen Shot 2023-02-15 at 9 22 35 AM" src="https://user-images.githubusercontent.com/6310006/219070992-32bfd225-eee2-462f-9d7f-6ea67df41cf2.png">

2023-02-23 19:47 UTC, singlerider approved these changes

2023-02-23 19:47 UTC, merged