Create Simple Interaction guide and add images
magicleap/developer-portal-docs pull request #214
Opened 2023-09-11 19:48 UTC by katvlasova

<img width="315" alt="Screenshot 2023-09-11 at 3 47 23 PM" src="https://github.com/magicleap/developer-portal-docs/assets/38482323/498ed93b-5d35-4207-b938-6556f6bb3f62">

2023-09-12 17:04 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +## Adding Controller Input
The script can be removed

2023-09-12 17:04 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +This document will demonstrate how to add grab interaction to the project created in the previous guide.
Add additional information and links to XRI possibly mention which things are supported through the standard XRI inputs (Controller and Head Pose) and things that are not (Hands and Eyes)

2023-09-12 17:05 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +This document will demonstrate how to add grab interaction to the project created in the previous guide.
You could try to create a standard XRI sample project and see which features work/don't work on Magic Leap 2

2023-09-12 17:09 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +2. Select the Grabbale Cube and in the inspector click **Add Component > XR Grab Interactable**. You can learn about this script in the [Unity XR Interaction Toolkit documentation](https://docs.unity
I would add a little more information than just asking the user to go to the XRI documentation. Possibly, mention :

What it does ie: Extends the XRI Interactable Class and translates the events into grab actions. For the actions to work properly, the input objects (the controller in this case) Requires the XR Controller and XR Ray Interactor components. The first script is to translate the input actions into generic XR Input events and the second script controls the Ray and the interactor's properties 
How it works

2023-09-12 17:10 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +3. In the scene hierarchy, right click in an empty space and select **XR > Interaction Manager** to add a new XR Interaction manager to the scene.
Possibly add information to what the XR Interaction Manager is and why it's required

2023-09-12 17:14 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +4. With the GrabbableCube selected, drag the newly created **XR Interaction Manager** object into the **Interaction Manager** slot on the **XR Grab Interactable** script on the cube.
Consider making the wording more generic. Something like:

Select the Grabbable Cube
Navigate to the XR Grab Interactable component and set the Interaction Manager to the newly created XR Interaction Manager Object

2023-09-12 17:24 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +5. Set the parameters to the following settings:
Explain what you are doing in this step and why. You could add something like 

Add a Box Collider for the XRI Interactable to receive input events from the XRI Ray Interactor 

Disable Use Gravity and Enable Is Kinematic to disable the object's physics interactions. This will prevent the object from falling to the ground or colliding with other objects when being manipulated. 

Move the image to the end

2023-09-12 17:25 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +
I would add the step of adding a Box collider here

2023-09-12 17:26 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +
You could move the step of creating the XR Interaction Manager here. Then make sure that it is set when you are creating the grabbable object to prevent going back and forth

2023-09-12 17:27 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +9. In the Inspector, find the **XR Ray Interactor** script attached to this object. Drag the **XR Interaction Manager** from the scene into the **XR Interaction Manager** slot in the script and **unc
Describe why you are disabling the Force Grab option

2023-09-12 17:29 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +8. Expand the XR Rig and select the **GameController** object.
Select the  **Game Controller** from the Hierarchy (`XR Rig/Session Origin/Game Controller`).

2023-09-12 17:33 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +## Adding Unity XR interaction
I would consider creating  2 sections.


1. Responding to XR Input Events by creating a cube and using the XR Simple Interactable Component 
    1. Create another cube as a child and place it above the cube. 
    2.  Use the component's Hover Entered and Hovered Exited Events to enable and disable the child cube.
    
2.  Creating a grabbable Cube

2023-09-12 17:33 UTC, Babilinski commented on static/img/unity/simple-app-interaction/gamecontroller.png
I would take another screen shot that shows the title of the window "Hierarchy"

2023-09-12 17:35 UTC, Babilinski commented on static/img/unity/simple-app-interaction/grabbable-cube-settings.png
If possible I would re-take this screenshot and make sure the Mesh filter is not selected so it's not highlighted blue. Additionally, I don't think you told users to made it a prefab in this tutorial

2023-09-12 17:35 UTC, Babilinski commented on static/img/unity/simple-app-interaction/xr-grab-interactable.png
Can you highlight the values that were mentioned in the guide ?

2023-09-12 17:41 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +This document will demonstrate how to add grab interaction to the project created in the previous guide.
It might be helpful to describe the end result. ie: This document provides step-by-step instructions on how to create a cube that can be selected, grabbed and manipulated , using Unity's XR Interaction toolkit and the sample project in the [Hello Cube guide](). By the end of this guide, developers should have a better understanding on how to use XRI to build and deploy Magic Leap 2 applications.

2023-09-13 17:30 UTC, katvlasova commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +## Adding Unity XR interaction
Changed to adding hover behavior in future commit

2023-09-14 03:18 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +This section will utilize a [Unity XR Interaction](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.4/manual/index.html) script allowing the user to grab the cube created in the p
I would add a small blurb of how the interactions will work to help the developer understand what you will be explaining in this section.  Something like mentioning that  you will use the XRI Rig and the XR Simple Interactable and that will get the On Hover Start and On Hover End events from the controllers XRI Ray Interactor.  You will also create a grabble cube using the XR Grabbable

2023-09-14 03:38 UTC, Babilinski requested changes
Just a few notes but it's looking really good ! We had a developer ask for a guide just like this today 👍

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +2. Add a box collider to the Grabbable Cube if it is not already present. This will allow for raycasts from the controller to be detected by the cube.
Instead of raycast mention the component that creates the raycast on the controller and possibly hyper link to it's documentation in the Unity docs

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +    - The [XR Interaction Manager](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.0/manual/xr-interaction-manager.html#:~:text=The%20Interaction%20Manager%20acts%20as,set%20of%2
Nice ! ♥

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +    - Set Collision Detection to *Continuous Dynamic* so the cube can continuously detect a raycast from the controller.
You might not need this step unless you are hitting the controller with a collider that is on the controller itself. 

(Optional) You could mention that the user should disable use gravity to prevent the object from falling to the ground when starting the application. In this sample we will ignore all physics interactions such as throwing by enabling Is Kinematic

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +10. In the Inspector, find the **XR Ray Interactor** script attached to this object. Drag the **XR Interaction Manager** from the scene into the **XR Interaction Manager** slot in the script and **un
I would break this up into 2 separate steps, 

10 In the Inspector, find the **XR Ray Interactor** script attached to this object. Drag the **XR Interaction Manager** from the scene into the **XR Interaction Manager** slot in the script 
11. **Deselect** the  *Force grab* option to  allow for xr interactables to be manipulated at a distance instead of sliding to the controllers location when grabbed.

<your image>

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +This will prevent the Cube from sliding to the location of the controller when grabbed and instead allow for it to be manipulated at a distance.
See comment above

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +One of the features of the XR Grab Interactable Script is that it allows the grabbed object to respond hover events. This section will explain how to change the Grabbable Cube's material on different
I know it wasn't part of the original scope but you could create a separate object to interact with using the Simple XR interactable to show how to receive events to create custom interactions. 

The changes would be creating another object and scaling and positioning it properly, then adding the simple xr interactable component

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +1. Create 3 new materials: Cyan (00FFFF), Magenta (FF00FF), and Yellow (FFFF00).
I would suggest adding a little more details 

1. Create 3 new materials (Assets >Create > Material)  and name them .....
2. Set the color of each of the materials to .... respectively

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +The final Hover actions will look like this:
You can remove this and only show the image

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +<img src="/img/unity/simple-app-interaction/hover-interactions.png" width="900"/>
Update the URLs for the images to use the following format. You can then remove the text that asks the user to look at the image and instead describe the image in the caption. 
```
<Image url= {require("/img/unity/simple-app-interaction/hover-interactions.png")} >The XR Grab Interactable with it's Hover events configured.</Image>
```

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +<img src="/img/unity/simple-app-interaction/grabbable-cube-settings.png" width="900"/>
Remove "Cube will look like this:"  and use the following image format

```
<Image url= {require("/img/unity/simple-app-interaction/grabbable-cube-settings.png")} >The Grabbable Cube's component hierarchy</Image>
```

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +<img src="/img/unity/simple-app-interaction/xr-grab-interactable.png" width="900"/>
Remove the ":" character and use the following image format
```
<Image url= {require("/img/unity/simple-app-interaction/xr-grab-interactable.png")} >The Smooth Settings inside the XR Grab Interactable Component </Image>
```

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +7. Set the parameters of the **XR Grab Interactable** script to the following settings for smooth movement of the cube:
Describe the smooth movement settings that were configured if different from the default values for search and for users that cannot see the image.

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +<img src="/img/unity/simple-app-interaction/rigidbody-settings.png" width="900"/>
<Image url= {require("/img/unity/simple-app-interaction/rigidbody-settings.png")} >The Grabbable Cube's rigidbody settings</Image>

2023-09-14 03:38 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +By the end of this guide, developers should have a better understanding on how to use the XR Grab Interactable script to allow Magic Leap 2 users to interact with gameobjects in the scene.
instead of gameobjects I would write objects or GameObjects

2023-09-14 04:31 UTC, ababilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +    - Set Collision Detection to *Continuous Dynamic* so the cube can continuously detect a raycast from the controller.
The explanation of **Continuous dynamic** is incorrect. Refer to [RigidbodyDoc](https://docs.unity3d.com/ScriptReference/Rigidbody.html)

1. Objects do not need a rigidbody to react to raycasts.
2. See DetectionMode doc: https://docs.unity3d.com/ScriptReference/Rigidbody-collisionDetectionMode.html
3. Is Kinematic can be turned on. "If isKinematic is enabled, Forces, collisions or joints will not affect the rigidbody anymore" See [Rigidbody isKinematic doc](https://docs.unity3d.com/ScriptReference/Rigidbody-isKinematic.html)
4.

2023-09-21 17:28 UTC, katvlasova commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +    - Set Collision Detection to *Continuous Dynamic* so the cube can continuously detect a raycast from the controller.
Thank you both! I left the Rigidbody on there because the project was originally spawning cubes that were colliding with each other as they were thrown around, will mark it as optional in the guide.

2023-09-21 19:04 UTC, Babilinski requested changes

2023-09-21 19:04 UTC, Babilinski commented on docs/guides/unity/getting-started/unity-simple-interaction.md
> +8. **Optional**: If you would like for the cube to react to physics forces, you can add a **[Rigidbody](https://docs.unity3d.com/ScriptReference/Rigidbody.html)** component to the cube.
To clarify:

The rigidbody component will be automatically added to the object when they add the XR Grab Interactor. I recommend asking developers to either enable **Is Kinematic** to prevent the object from reacting to physics forces such as velocity and gravity. 

8. Enable **Is Kinematic** on the Grabbable Cube's  **[Rigidbody](https://docs.unity3d.com/ScriptReference/Rigidbody.html)** to prevent the object from falling to the ground at the 
 start of the application and ignore forces such as velocity.

2023-09-22 16:12 UTC, Babilinski approved these changes

2023-09-26 20:08 UTC, Babilinski approved these changes
LGTM

2023-09-26 20:09 UTC, merged