Add Remote Rendering Documentation (Do not Merge)
magicleap/developer-portal-docs pull request #51
Opened 2023-03-14 15:59 UTC by singlerider

This PR has a dependency on the deployment/delivery mechanism of the software before it can go live.

<img width="1321" alt="Screen Shot 2023-03-14 at 9 59 23 AM" src="https://user-images.githubusercontent.com/6310006/225063098-365d6c59-e8b3-4b4d-a9b5-f06f6216e728.png">
<img width="250" alt="Screen Shot 2023-03-14 at 9 59 12 AM" src="https://user-images.githubusercontent.com/6310006/225063124-fe4de89b-cc2b-498a-8535-d6541579c9bd.png">

2023-03-14 18:25 UTC, rbridgewaterML commented on docs/guides/remote-rendering/remote-rendering.md
> +Currently, Remote Rendering can on ly be performed using Windows.
on ly -> only

2023-03-14 18:36 UTC, rbridgewaterML requested changes

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/remote-rendering.md
> +qualities, and allows enterprise customers to reuse existing 3D assets without modification,
Do we want "Enterprise" in our dev docs? We include this for the sake of describing internally the focus

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/remote-rendering.md
> +such as Unreal Engine, Omniverse, Blender, Maya, and more.
Should mention this is an OpenXR runtime

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +Windrunner is a first-party tool, created by Magic Leap, designed to allow for rendering content onto a Magic Leap 2 device from a more-powerful, non-mobile Windows computer.
Don't mention Windrunner

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +| GPU               |     Any RTX Card      | 2x GeForce RTX 3090 or higher |
These are the Omniverse min-spec. You should set this differently than listed, we have tested with 1080s on simple apps.

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +| Bandwidth up/down |      1 GB Wifi 6      |          1 GB Wifi 6          |
Bandwidth up/down implies a number but you list an adapter.

Wifi 5 should be fine as long as it is the 5ghz band

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +\* Run `nvidia-smi.exe` in a command prompt to get the Nvidia Driver Version.
Would likely be b est to not point to nvidia-smi.exe for external users. They may manage this with Nvidia applications for easier gui use.

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +### Remote Viewer Thin Client
Should secure buy in on the public name of this

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +- [Learn how to install applications](https://developer-docs.magicleap.cloud/docs/guides/developer-tools/ml-hub/ml-hub-device-bridge#use-device-bridge)
The client app install will be automated from the Hub

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +1. Locate [Windrunner-0.1.0-win64.exe](TODO). in the shared folder
This will be done from The Hub for R6 for easier usage. These instructions WERE true for early access customers while R6 was in development

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +Bridge.
Suggestion: Show a pic how to

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +#### Running using PowerShell
We should likely not display this, or at least not prominently. The hub is the expected user interface

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +4. Right click on `windrunner-service.exe` and select **Run as administrator**
No, it should not be run as admin. This will create issues.

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +Only applications developed for Remote Rendering are able to be streamed to the device.
This is incorrect entirely. Any Vulkan OpenXR app should work.

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +1. Locate the `MotorcycleDemo_Windows.zip` in the shared folder
We should likely point to a different example app unless we are certain we are going with this one (And that we have an appropriate license for the app to use it this way)

We had an old pending task to perhaps publish artifacts of HelloXR, perhaps a slightly modified one with the right args by default.

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +Run the Magic Leap Hub as an administrator.
No! Admin can cause very strange IPC issues.

Please share with me where you saw this so I can scrub it from our internal docs, if you got it there.

2023-03-14 18:36 UTC, rbridgewaterML commented on docs/guides/remote-rendering/windrunner.md
> +Resolve the issue by following these steps:
Again, the Hub manages this for you

2023-03-14 18:36 UTC, rbridgewaterML commented on static/img/remote-rendering/windrunner-installation.png
Needs a new screenshot without Windrunner name.

Likely we should hard-code the version to 1.0.0 as we will for release.

2023-03-15 18:18 UTC, ababilinski commented on docs/guides/remote-rendering/windrunner.md
> +Run the Magic Leap Hub as an administrator.
Strange - I had to do this to get it working. Otherwise the app did not connect to the Magic Leap.

2023-03-15 18:27 UTC, ababilinski commented on docs/guides/remote-rendering/windrunner.md
> +Resolve the issue by following these steps:
This issue occurs when running the PowerShell script.

Reasons this occurs:
- The Hub auto connects the wifi bridge automatically (without the user toggling it) causing 2 adb devices
- The user tried to connect with The Hub and then switched to use the PowerShell script

2023-03-15 18:28 UTC, ababilinski commented on static/img/remote-rendering/windrunner-installation.png
What is the official name of the app?

2023-03-17 17:22 UTC, closed without merging

2023-03-17 17:22 UTC, ababilinski commented
Closing Pull Request until the tools are available on The Magic Leap Hub